### ISSUE TITLE
TypeError during installation in Trac 0.12.3

### ISSUE THREAD

**Issue by mapkon** [jszakmeister/trac-backlog#10]
During installation, this error is thrown:

0.3.0_dev-py2.7.egg\backlog\schema.py", line 16, in <module>
TypeError: **init**() got an unexpected keyword argument 'unique'

A related ticket here: http://trac-hacks.org/ticket/7276

**Comment by mapkon** [comment]
I have a diff to address this issue. I can make a pull request!

**Comment by jszakmeister** [comment]
This has been fixed on master for a while.  BTW, I've just pushed up version 0.3.0 and made it available via PyPI.
