### ISSUE TITLE
backlog does not work with postgresql

### ISSUE THREAD

**Issue by mgexo** [jszakmeister/trac-backlog#13]
Hello,

Id like to use your backlog plugin in our company.

I can install backlog correctly, but when I click on "Backlog" Icon in trac, I get the following error message:

"Zero length delimited identifier"

I suppose the reason is, that you use double-quotes instead of single quotes in your SQL statement, according to this post:

http://www.postgresql.org/message-id/20030505103640.P87200-100000@megazone23.bigpanda.com

Would it be possible for you to fix that?

Thanks!

mgex

**Comment by jszakmeister** [comment]
I'll try and take a look at this tomorrow or Thursday.  Thanks for the report!

**Comment by jszakmeister** [comment]
Can you give master a whirl?  b10da59b317025892a3b3324cd0c04eb87495359 fixed the only occurrence of a double quote that I could find.

**Comment by mgexo** [comment]
Ok, your fix repaired the "Zero length delimiter" bug. 

Now I get a new different error message:

ProgrammingError: operator does not exist: bigint == integer LINE 2: WHERE completed == 0 ^ HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts.

stack:

File "/usr/local/lib/python2.7/dist-packages/Trac-0.12-py2.6.egg/trac/web/main.py", line 513, in _dispatch_request
File "/usr/local/lib/python2.7/dist-packages/Trac-0.12-py2.6.egg/trac/web/main.py", line 235, in dispatch
File "/usr/local/lib/python2.7/dist-packages/TracBacklog-0.4.0_dev-py2.7.egg/backlog/web_ui.py", line 210, in process_request
File "/usr/local/lib/python2.7/dist-packages/TracBacklog-0.4.0_dev-py2.7.egg/backlog/web_ui.py", line 373, in _get_active_milestones
File "/usr/local/lib/python2.7/dist-packages/Trac-0.12-py2.6.egg/trac/db/util.py", line 66, in execute

**Comment by mgexo** [comment]
P.S. 

I fixed this bug with the following diff (remove double-equals and doing a cast to bigint):

diff --git a/backlog/web_ui.py b/backlog/web_ui.py
index d366ded..f6b612a 100644
--- a/backlog/web_ui.py
+++ b/backlog/web_ui.py
@@ -42,8 +42,8 @@ UNSCHEDULED_BACKLOG_QUERY = '''SELECT id FROM ticket t
 '''

 MILESTONE_QUERY = '''SELECT name, due FROM milestone
-  WHERE completed == 0
-  ORDER BY (due == 0), due, UPPER(name), name
-  WHERE completed = CAST(0 AS bigint)
-  ORDER BY (due = 0), due, UPPER(name), name
  '''

**Comment by jszakmeister** [comment]
On Thu, Mar 21, 2013 at 2:33 PM, mgex notifications@github.com wrote:
[snip]

> I fixed this bug with the following diff (remove double-equals and doing a
> cast to bigint):
> 
> diff --git a/backlog/web_ui.py b/backlog/web_ui.py
> index d366ded..f6b612a 100644
> --- a/backlog/web_ui.py
> +++ b/backlog/web_ui.py
> @@ -42,8 +42,8 @@ UNSCHEDULED_BACKLOG_QUERY = '''SELECT id FROM ticket t
> '''
> 
> MILESTONE_QUERY = '''SELECT name, due FROM milestone
> 
> WHERE completed == 0
> ORDER BY (due == 0), due, UPPER(name), name
> WHERE completed = CAST(0 AS bigint)
> ORDER BY (due = 0), due, UPPER(name), name '''

Did it not work without the cast and just changing it to single
equals?  Also, I wonder if this is because of a change in Trac's
schema?  I might have to be more clever in doing this query.

-John

**Comment by mgexo** [comment]
Sorry, I am not sure if the cast is necessary (actually I tried the cast first after noticing the double equal sign problem, then I left the cast there).

Anyway, the backlog seems to work correctly now with our system, and we will start the company evaluation phase (we have a small team of 8 developers).  Thanks for your feedback and fast help!

**Comment by jszakmeister** [comment]
I checked in the removal of the double equals, but left out the cast.  If you get a chance, it'd be nice to know if that works with the postgresql setup better.
