### ISSUE TITLE
trac-backlog is broken on 0.12.x

### ISSUE THREAD

**Issue by jszakmeister** [jszakmeister/trac-backlog#2]
Not sure where the issue is.  The changelog didn't mention any changes related to `IEnvironmentSetupParticipant`, but something has changed.  It appears the navigation related bits are missing to.

**Comment by jaylett** [comment]
Looks to me like moving to `unique=True` on a `Column` definition doesn't work in 0.12; I killed that and put an explicit `Index` definition in to cover the uniqueness, and it seems to be working fine for me in 0.12.2.

**Comment by jszakmeister** [comment]
Interesting.  Thanks for the info James!
